
# Permissions:
# - spawnerDrops.admin  (allows placing of spawners as source ADMIN)

# Necessary permission:
# - minecraft.nbt.place  (allows placing block with NBT-data)


break:
  # Prerequisites for breaking a spawner from different sources
  # If the prerequisite is not met, the event is canceled and the block stays where is is -> 'nothing' happens
  break-prerequisite:
    # 'unknown' means we dont know where the spawner came from (usually a generated one or e.g. using worldedit)
    UNKNOWN:
      # If a spawner can be broken at all (displays fail-message if set)
      canBreak: true
      # Which items are allowed to break a spawner (null to allow everything)
      allowed-items:
        - 'diamond_pickaxe'
      # silktouch-enchantment is needed to be able to break this block
      # if everything is set to false, any break is considered a 'success'
      silktouch: true
      # messages for success or failure
      msg:
        success: ''
        fail: '§7§oNothing happens, it seems you need a diamond-pickaxe with silktouch'

    PLAYER:
      canBreak: true
      allowed-items:
        - 'diamond_pickaxe'
      silktouch: true
      msg:
        success: ''
        fail: '§7§oNothing happens, it seems you need a diamond-pickaxe with silktouch'

    ADMIN:
      canBreak: true
      allowed-items:
        - 'diamond_pickaxe'
      silktouch: true
      msg:
        success: ''
        fail: '§7§oNothing happens, it seems you need a diamond-pickaxe with silktouch'


  drop:
    item:
      name: '{mob-type}-Spawner'

  # Prerequisites for a successful drop of the spawner-item AFTER (and only if) it was broken
  # (if a player can break it, but the drop prerequisite is not met, the block is broken, but no item will drop -> Its lost)
  drop-prerequisite:

    UNKNOWN:
      # If a spawner ever drops the item (displays fail-message if set)
      willDrop: true
      allowed-items:
        - 'diamond_pickaxe'
      silktouch: true
      msg:
        success: '§7§oThe spawner breaks with a loud *Pop* and falls to the ground to be picked up'
        fail: '§7§o*Poof* The spawner breaks into many pieces and is lost'

    PLAYER:
      willDrop: true
      allowed-items:
        - 'diamond_pickaxe'
      silktouch: true
      msg:
        success: ''
        fail: '§7§o*Poof* The spawner breaks into many pieces and is lost'

    ADMIN:
      willDrop: true
      allowed-items:
        - 'diamond_pickaxe'
      silktouch: true
      msg:
        success: '§7§oThe spawner breaks with a loud *Pop* and falls to the ground to be picked up'
        fail: '§7§o*Poof* The spawner breaks into many pieces and is lost'


place:
  PLAYER:
    canPlace: true
    msg:
      success: ''
      fail: '§7§oNothing happened.. You dont seem to be able to place spawners'
  ADMIN:
    msg:
      success: '§7§oMineable spawner placed'
