

break:
  # Prerequisites for breaking a spawner from different sources
  # If the prerequisite is not met, the event is canceled and the block stays where is is -> 'nothing' happens
  break-prerequisite:
    # 'unknown' means we dont know where the spawner came from (usually a generated one or e.g. using worldedit)
    UNKNOWN:
      # silktouch-enchantment is needed to be able to break this block
      # if set to false, any break is considered a 'success'
      silktouch: true
      # messages for success or failure
      msg:
        success: ''
        fail: '§7§oNothing happens, it seems you cannot break the spawner without the Silktouch-enchantment'

    PLAYER:
      silktouch: true
      msg:
        success: ''
        fail: '§7§oNothing happens, it seems you cannot break the spawner without the Silktouch-enchantment'

    ADMIN:
      silktouch: true
      msg:
        success: ''
        fail: '§7§oNothing happens, it seems you cannot break the spawner without the Silktouch-enchantment'


  # Prerequisites for a successful drop of the spawner-item AFTER (and only if) it was broken
  # (if a player can break it, but the drop prerequisite is not met, the block is broken, but not item will drop -> Its lost)
  drop-prerequisite:

    UNKNOWN:
      silktouch: true
      msg:
        success: '§7§oThe spawner breaks with a loud *Pop* and falls to the ground to be picked up'
        fail: '§7§o*Poof* The spawner breaks into many pieces and is lost'

    PLAYER:
      silktouch: true
      msg:
        success: ''
        fail: '§7§o*Poof* The spawner breaks into many pieces and is lost'

    ADMIN:
      silktouch: true
      msg:
        success: '§7§oThe spawner breaks with a loud *Pop* and falls to the ground to be picked up'
        fail: '§7§o*Poof* The spawner breaks into many pieces and is lost'


place:
  PLAYER:
    canPlace: true
    msg:
      success: ''
      fail: '§7§oNothing happened.. You dont seem to be able to place spawners'
  ADMIN:
    msg:
      success: '§7§oMineable spawner placed'
